dist: xenial

language: elixir

elixir:
  - 1.17.3
  - 1.18.1

otp_release:
  - 25.3
  - 26.2.5
  - 27.2

env:
  global:
    - MIX_ENV=test
    - NODE_VERSION=10.15.3

before_install:
  - nvm install $NODE_VERSION

script:
  - npm install
  - mix coveralls
